### GET USER
GET http://localhost:3000/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NTcxNTQxMjEsImV4cCI6MTY1NzE1NDE4MX0.TIFtqfPdvpEbYZjHSPna1sOcSMf9OIMzT0tP7y6LlEY


### POST CREATE USER
POST http://localhost:3000/user
Content-Type: application/json

{
    "name":"teste",
    "email":"vitor@teste.com",
    "password":"novo"
}


### Get One User
GET http://localhost:3000/user/teste4dependencies@teste.com
Content-Type: application/json


### POST USER LOGIN
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "name":"teste",
    "email":"vitor@teste.com",
    "password":"novo"
}


### POST auth LOGIN
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "name":"teste",
    "email":"vitor@teste.com",
    "password":"novo"
}

### Create a product
POST http://localhost:3000/product
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlIiwic3ViIjo5LCJpYXQiOjE2NTgzMjc2ODEsImV4cCI6MTY1ODQxNDA4MX0.qIP6ZFdatjlBKYQZl_lUhWeBAoi64HAhP_UIMtlGZ14

{
    "name": "produto 1",
    "value": 10.0,
    "amount":2,
    "characters":["produto","bom", "qualidade"],
    "detail": "Aquele produto de respeito",
    "category": "Eletronico"  
}